apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-runboat-postgres-local
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  dataLocality: strict-local
  fsType: ext4
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
